# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

dist: jammy
language: rust
services: docker

env:
  global:
    - CRATE_NAME=cccp

matrix:
  include:
    # OSX
    # - env: TARGET=i686-apple-darwin
    - env: TARGET=x86_64-apple-darwin # no tests
    - env: TARGET=aarch64-apple-darwin # no tests

    # Windows
    - env: TARGET=x86_64-pc-windows-gnu
    - env: TARGET=i686-pc-windows-gnu
    - env: TARGET=x86_64-pc-windows-msvc DISABLE_TESTS=1
    - env: TARGET=i686-pc-windows-msvc DISABLE_TESTS=1
    - env: TARGET=aarch64-pc-windows-msvc DISABLE_TESTS=1

    # Linux
    - env: TARGET=aarch64-unknown-linux-gnu
    - env: TARGET=aarch64-unknown-linux-musl
    - env: TARGET=arm-unknown-linux-gnueabi
    - env: TARGET=armv7-unknown-linux-gnueabihf
    - env: TARGET=i686-unknown-linux-musl
    - env: TARGET=mips-unknown-linux-musl # no tests
    - env: TARGET=mipsel-unknown-linux-musl # no tests
    - env: TARGET=mips64-unknown-linux-gnuabi64
    - env: TARGET=mips64el-unknown-linux-gnuabi64
    - env: TARGET=powerpc-unknown-linux-gnu
    - env: TARGET=powerpc64-unknown-linux-gnu
    - env: TARGET=powerpc64le-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-linux-musl
    - env: TARGET=x86_64-unknown-linux-gnu

    # *BSD
    - env: TARGET=i686-unknown-freebsd DISABLE_TESTS=1
    - env: TARGET=x86_64-unknown-freebsd DISABLE_TESTS=1
    - env: TARGET=x86_64-unknown-netbsd DISABLE_TESTS=1

before_install:
  - sudo systemctl stop docker.service && sudo systemctl stop docker.socket
  - for pkg in docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc; do sudo apt-get remove $pkg; done
  - wget https://download.docker.com/linux/ubuntu/dists/jammy/pool/stable/amd64/docker-ce_20.10.24~3-0~ubuntu-jammy_amd64.deb
  - wget https://download.docker.com/linux/ubuntu/dists/jammy/pool/stable/amd64/docker-ce-cli_20.10.24~3-0~ubuntu-jammy_amd64.deb
  - wget https://download.docker.com/linux/ubuntu/dists/jammy/pool/stable/amd64/docker-buildx-plugin_0.11.2-1~ubuntu.22.04~jammy_amd64.deb
  - wget https://download.docker.com/linux/ubuntu/dists/jammy/pool/stable/amd64/docker-compose-plugin_2.6.0~ubuntu-jammy_amd64.deb
  - wget https://download.docker.com/linux/ubuntu/dists/jammy/pool/stable/amd64/containerd.io_1.6.9-1_amd64.deb
  - yes | sudo dpkg -i containerd.io_1.6.9-1_amd64.deb docker-ce_20.10.24~3-0~ubuntu-jammy_amd64.deb docker-ce-cli_20.10.24~3-0~ubuntu-jammy_amd64.deb docker-buildx-plugin_0.11.2-1~ubuntu.22.04~jammy_amd64.deb docker-compose-plugin_2.6.0~ubuntu-jammy_amd64.deb
  - sudo systemctl status docker.service
  - set -e
  - rustup self update
  - rustup component add rustfmt

install:
  - source ~/.cargo/env || true
  - sh ci/install.sh

script:
  - bash ci/script.sh

after_script: set +e

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  api_key:
    secure: gCv8cVWxx3HL4lFw0gwC5vIl4tyyPTG2ulquxZbrzRBeob6Ys39Rj9KBYis4bY44jXFKNBMbmyCKPGB6l5hoqTCKk2T5evOauWrZm1m2nzzRgeZ5OSKOpFMevO8rJA7Kc52lOvrdBtmhpnNjo9J5FDrc6N28u3TBhZ3DUqhCFMSs6GfXBCLbK7pIGcZeeNSujfoRx9tiF2AdXcbD9Pn3jSXRozvcItjqfjMEyBFqyAhVz4dDvEb/TiCdqyffs7Xr1Er886xEIdDv4i5g6T+SAQDj2+2/8W4nysjArIYMxIRcqDBqaHd07tHPg5AWZDq4Wg9knpzA5Hu7UXv00iSejPsbzElxwHa3oyTF0yIGyldt4qe7/ru593TTOZXS8Cwo7EsYdfUWrfhsl/4otGet/Ta/QaBeHwf6Sx1e6IPstbIwzvfI0jG2VE8yBO4Afb/BkS2Ufwawxt1KoXOP8ES+I+UR05M4shGBvNvZLqCftH7TUPlgpRmZGVz5OOgPi7UFOm19Qf3IPDS/8GlDN+T1wzNQbVTrU+qP6ah0mPEXOwrJeLF2fNDiQzVFgl/mg60osFHHmLwKcAxPzkkZjtCbIt830PRgg43W8yTDERnorvw/IdfLOvu0ngseFER8p8iN16M3IvDcKJ3HKGkURN5gBAqdtLA56HZdAj21uD+waXw=
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  on:
    condition: $TRAVIS_RUST_VERSION = nightly
    tags: true
  provider: releases
  cleanup: false

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - main

notifications:
  email:
    on_success: never