[package]
name = "cccp"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4", features = ["derive"] }
tokio = { version = "1.34", default-features = false, features = ["macros", "fs", "io-util"] }
futures = "0.3"
log = { version = "0.4", features = ["std"] }
async-ssh2-tokio = "0.8"
simple-logging = "2.0"
deadqueue = "0.2"
regex = "1.10"
dirs = "5.0"
rpassword = "7.3"
indicatif = "0.17"
prost = "0.12"
prost-build = "0.12"
bytesize = "1.3.0"
kanal = "0.1.0-pre8"

[build-dependencies]
prost-build = "0.12.3"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1