[package]
name = "cccp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.8", features = ["derive"] }
tokio = { version = "1.34.0", features = ["full"] }
futures = "0.3.29"
log = { version = "0.4.20", features = ["std"] }
async-ssh2-tokio = "0.8.3"
simple-logging = "2.0.2"
deadqueue = "0.2.4"
regex = "1.10.2"
reqwest = { version = "0.11.22", default-features = false }
dirs = "5.0.1"
async-channel = "2.1.0"
rpassword = "7.3.1"
indicatif = "0.17.7"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1