[target.aarch64-unknown-linux-gnu]
dockerfile = "ci/LinuxDockerFile"

[target.aarch64-unknown-linux-musl]
dockerfile = "ci/LinuxDockerFile"

[target.arm-unknown-linux-gnueabi]
dockerfile = "ci/LinuxDockerFile"

[target.armv7-unknown-linux-gnueabihf]
dockerfile = "ci/LinuxDockerFile"

[target.i686-unknown-linux-musl]
dockerfile = "ci/LinuxDockerFile"

[target.mips-unknown-linux-musl]
build-std = true
dockerfile = "ci/LinuxDockerFile"

[target.mipsel-unknown-linux-musl]
dockerfile = "ci/LinuxDockerFile"
build-std = true

[target.mips64-unknown-linux-gnuabi64]
dockerfile = "ci/LinuxDockerFile"
build-std = true

[target.mips64el-unknown-linux-gnuabi64]
dockerfile = "ci/LinuxDockerFile"
build-std = true

[target.powerpc-unknown-linux-gnu]
dockerfile = "ci/LinuxDockerFile"

[target.powerpc64-unknown-linux-gnu]
dockerfile = "ci/LinuxDockerFile"

[target.powerpc64le-unknown-linux-gnu]
dockerfile = "ci/LinuxDockerFile"

[target.x86_64-unknown-linux-musl]
dockerfile = "ci/LinuxDockerFile"

[target.x86_64-unknown-linux-gnu]
dockerfile = "ci/LinuxDockerFile"

[target.i686-unknown-freebsd]
dockerfile = "ci/LinuxDockerFile"

[target.x86_64-unknown-freebsd]
dockerfile = "ci/LinuxDockerFile"

[target.x86_64-unknown-netbsd]
dockerfile = "ci/LinuxDockerFile"
pre-build = [
    "mkdir -p /tmp/netbsd",
    "curl https://cdn.netbsd.org/pub/NetBSD/NetBSD-9.2/amd64/binary/sets/base.tar.xz -O",
    "tar -C /tmp/netbsd -xJf base.tar.xz",
    "cp /tmp/netbsd/usr/lib/libexecinfo.so /usr/local/x86_64-unknown-netbsd/lib",
    "rm base.tar.xz",
    "rm -rf /tmp/netbsd",
]

[target.x86_64-pc-windows-gnu]
dockerfile = "ci/LinuxDockerFile"

[target.i686-pc-windows-gnu]
dockerfile = "ci/LinuxDockerFile"