[target.aarch64-unknown-linux-gnu.dockerfile]
file = "ci/LinuxDockerFile"

[target.arm-unknown-linux-gnueabi.dockerfile]
file = "ci/LinuxDockerFile"

[target.arm-unknown-linux-gnueabihf.dockerfile]
file = "ci/LinuxDockerFile"

[target.armv7-unknown-linux-gnueabihf.dockerfile]
file = "ci/LinuxDockerFile"

[target.i686-unknown-linux-musl.dockerfile]
file = "ci/LinuxDockerFile"

[target.mips-unknown-linux-gnu.dockerfile]
file = "ci/LinuxDockerFile"

[target.mips64-unknown-linux-gnuabi64.dockerfile]
file = "ci/LinuxDockerFile"

[target.mips64el-unknown-linux-gnuabi64.dockerfile]
file = "ci/DarwinDockerFile"

[target.mipsel-unknown-linux-gnu.dockerfile]
file = "ci/WindowsDockerFile"

[target.powerpc-unknown-linux-gnu.dockerfile]
file = "ci/WindowsDockerFile"

[target.powerpc64-unknown-linux-gnu.dockerfile]
file = "ci/WindowsDockerFile"

[target.powerpc64le-unknown-linux-gnu.dockerfile]
file = "ci/WindowsDockerFile"

[target.x86_64-unknown-linux-musl.dockerfile]
file = "ci/WindowsDockerFile"

[target.x86_64-pc-windows-gnu.dockerfile]
file = "ci/WindowsDockerFile"

[target.i686-unknown-freebsd.dockerfile]
file = "ci/WindowsDockerFile"

[target.x86_64-unknown-freebsd.dockerfile]
file = "ci/WindowsDockerFile"

[target.x86_64-unknown-netbsd.dockerfile]
file = "ci/WindowsDockerFile"