[target.aarch64-unknown-linux-gnu]

[target.aarch64-unknown-linux-musl]

[target.arm-unknown-linux-gnueabi]

[target.armv7-unknown-linux-gnueabihf]

[target.i686-unknown-linux-musl]

[target.mips-unknown-linux-musl]
build-std = true

[target.mipsel-unknown-linux-musl]
build-std = true

[target.mips64-unknown-linux-gnuabi64]
build-std = true

[target.mips64el-unknown-linux-gnuabi64]
build-std = true

[target.powerpc-unknown-linux-gnu]

[target.powerpc64-unknown-linux-gnu]

[target.powerpc64le-unknown-linux-gnu]

[target.x86_64-unknown-linux-musl]

[target.x86_64-unknown-linux-gnu]

[target.x86_64-pc-windows-gnu]

[target.i686-pc-windows-gnu]

[target.i686-unknown-freebsd]

[target.x86_64-unknown-freebsd]

[target.x86_64-unknown-netbsd]